"""create status_table

Revision ID: b3f93734e8f4
Revises: b9929da5ad3b
Create Date: 2026-03-06 10:26:30.389225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b3f93734e8f4'
down_revision: Union[str, Sequence[str], None] = 'b9929da5ad3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authz_status',
    sa.Column('status_id', mysql.TINYINT(unsigned=True), autoincrement=True, nullable=False, comment='ID del estatus (tinyint 0-255)'),
    sa.Column('status_name', sa.String(length=100), nullable=True, comment='Nombre único del estatus'),
    sa.Column('status_description', sa.String(length=255), nullable=True, comment='Descripción opcional del estatus'),
    sa.PrimaryKeyConstraint('status_id'),
    sa.UniqueConstraint('status_name'),
    comment='Tabla de estados generales del sistema (activo, inactivo, etc.)',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authz_status')
    # ### end Alembic commands ###
