"""create audit_admin table

Revision ID: b9929da5ad3b
Revises: 
Create Date: 2026-02-26 10:59:22.285004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b9929da5ad3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_admin',
    sa.Column('audit_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='Audit row id'),
    sa.Column('event_id', sa.String(length=32), nullable=True, comment='Correlation id for the audit event (uuid4().hex)'),
    sa.Column('actor_id', mysql.BIGINT(unsigned=True), nullable=True, comment='User id of the actor (who performed the action)'),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='UTC timestamp'),
    sa.Column('view_id', mysql.INTEGER(unsigned=True), nullable=False, comment='Vista desde la cual se realizó la acción'),
    sa.Column('table_name', sa.String(length=128), nullable=False, comment='Target table/resource name (e.g. users)'),
    sa.Column('record_id', mysql.BIGINT(unsigned=True), nullable=False, comment='Target record id (user_id)'),
    sa.Column('action', sa.String(length=16), nullable=False, comment='insert|update|delete|read|error'),
    sa.Column('field_name', sa.String(length=128), nullable=True, comment='Changed field name (for update/insert)'),
    sa.Column('value', sa.Text(), nullable=True, comment="New value / '1' / JSON / etc"),
    sa.Column('meta', sa.Text(), nullable=True, comment='JSON string with extra context (endpoint, view_id, error, etc.)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP (v4/v6)'),
    sa.PrimaryKeyConstraint('audit_id'),
    comment='Audit log for users resource',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_audit_admin_action_created', 'audit_admin', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_admin_actor_created', 'audit_admin', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_audit_admin_event_created', 'audit_admin', ['event_id', 'created_at'], unique=False)
    op.create_index('ix_audit_admin_event_id', 'audit_admin', ['event_id'], unique=False)
    op.create_index('ix_audit_admin_table_record', 'audit_admin', ['table_name', 'record_id'], unique=False)
    op.create_index('ix_audit_admin_table_record_created', 'audit_admin', ['table_name', 'record_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_admin_table_record_created', table_name='audit_admin')
    op.drop_index('ix_audit_admin_table_record', table_name='audit_admin')
    op.drop_index('ix_audit_admin_event_id', table_name='audit_admin')
    op.drop_index('ix_audit_admin_event_created', table_name='audit_admin')
    op.drop_index('ix_audit_admin_actor_created', table_name='audit_admin')
    op.drop_index('ix_audit_admin_action_created', table_name='audit_admin')
    op.drop_table('audit_admin')
    # ### end Alembic commands ###
